### ISSUE TITLE
Support native push notifications

### ISSUE THREAD

**Issue by WillSewell** [pusher-community/pusher-http-haskell#39]
Need to wrap the API documented here: https://pusher.com/docs/push_notifications/reference/server_api

If you want to get involved and have any questions, let me know.

**Comment by narrative** [comment]
I see you self-assigned this, but are you open to PRs? If so, I can show what I have done so far and perhaps you can provide feedback.

**Comment by WillSewell** [comment]
Hi @narrative I would definitely be open to PRs. I haven't made any progress on this so far.

I would imagine this would involve adding a new function to the main module that corresponds to the API request to send a push notification. The general flow should follow the existing public functions and their implementations.

**Comment by WillSewell** [comment]
Done in https://github.com/pusher-community/pusher-http-haskell/pull/50.
