### ISSUE TITLE
compile error with GHC 7.8

### ISSUE THREAD

**Issue by hvr** [pusher-community/pusher-http-haskell#45]
I just noticed the compile failure below with GHC 7.8/base-4.7's default install-plan; I haven't investigated further yet

```
Configuring component lib from pusher-http-haskell-1.1.0.4...
Preprocessing library pusher-http-haskell-1.1.0.4...

src/Network/Pusher.hs:81:8:
    Could not find module ‘Control.Monad.Trans.Except’
    It is a member of the hidden package ‘transformers-0.5.2.0’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.4.3.0’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-compat-0.5.1.3’.
    Perhaps you need to add ‘transformers-compat’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

PS: GHC 7.8's default install-plan most likely picked `transformers-0.3`, so this may just be a matter of tightening the lower bound on `transformers`

**Comment by WillSewell** [comment]
Ah yes you are right. This is no longer backwards compatible with GHC 7.8/base-4.7, but the lower bounds of dependencies have not been tightened. I'll fix this.

**Comment by WillSewell** [comment]
Fixed here: https://github.com/pusher-community/pusher-http-haskell/pull/48.

**Comment by hvr** [comment]
@WillSewell 

I just realised I never followed up here to point out that metadata revisions are required to address the issue!

Since I've noticed you don't seem to have ever performed a metadata revision on Hackage, here's a useful link: https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md

Below is a screenshot of the original build matrix report from https://matrix.hackage.haskell.org/package/pusher-http-haskell where basically each red cell is a problem that needs to be fixed via metadata revisions. In my function as Hackage Trustee I've performed revisions to all the affected releases:

 - https://hackage.haskell.org/package/pusher-http-haskell-1.0.0.0/revisions/
 - https://hackage.haskell.org/package/pusher-http-haskell-1.1.0.0/revisions/
 - https://hackage.haskell.org/package/pusher-http-haskell-1.1.0.1/revisions/
 - https://hackage.haskell.org/package/pusher-http-haskell-1.1.0.2/revisions/
 - https://hackage.haskell.org/package/pusher-http-haskell-1.1.0.3/revisions/
 - https://hackage.haskell.org/package/pusher-http-haskell-1.1.0.4/revisions/
 - https://hackage.haskell.org/package/pusher-http-haskell-1.2.0.0/revisions/
 - https://hackage.haskell.org/package/pusher-http-haskell-1.2.0.1/revisions/
 - https://hackage.haskell.org/package/pusher-http-haskell-1.3.0.0/revisions/
 - https://hackage.haskell.org/package/pusher-http-haskell-1.4.0.0/revisions/
 - https://hackage.haskell.org/package/pusher-http-haskell-1.5.0.0/revisions/
 - https://hackage.haskell.org/package/pusher-http-haskell-1.5.0.1/revisions/
 - https://hackage.haskell.org/package/pusher-http-haskell-1.5.1.0/revisions/
 - https://hackage.haskell.org/package/pusher-http-haskell-1.5.1.1/revisions/
 - https://hackage.haskell.org/package/pusher-http-haskell-1.5.1.2/revisions/
 - https://hackage.haskell.org/package/pusher-http-haskell-1.5.1.3/revisions/
 - https://hackage.haskell.org/package/pusher-http-haskell-1.5.1.4/revisions/
 - https://hackage.haskell.org/package/pusher-http-haskell-1.5.1.5/revisions/

Please let me know if you have any questions!

![report](https://user-images.githubusercontent.com/285533/46261318-42675c80-c4f2-11e8-8ffb-8506199de01c.png)

**Comment by WillSewell** [comment]
Ah, I was not aware that you could tweak bounds of existing releases through metadata revisions. Thanks for doing this for me!

**Comment by hvr** [comment]
@WillSewell you're welcome! Btw, do you have any suggestion how we could have advertise the metadata revision feature better on Hackage so e.g. you would have noticed this earlier?

**Comment by WillSewell** [comment]
It wasn't obvious to me that clicking "edit package information" would allow me to change metadata that was defined in the cabal file. It would have been more obvious this is editable if there was a more prominent link under the location where this metadata is displayed, e.g. if there was a link to "revise dependencies" under the location on the page where the dependencies are listed.

It would also be helpful if there was a bullet of the kinds of metadata that can be edited after a version is published in the "Maintainer's Corner" section of the root of the package page.
