### ISSUE TITLE
Update the link of `get` method in "Unit testing IO in Haskell" post

### ISSUE THREAD

**Issue by yigitozkavci** [pusher-community/pusher-http-haskell#53]
In the post, `get` method link has address of the master tree of the git repo, which is misleading since post is from 29 September 2015, and many has been changed since then.

I suggest making link a constant by using the following link, which is the repo state from the last commit before writing time of the post:

https://github.com/pusher-community/pusher-http-haskell/blob/3498b74afccef0424766370b3a797cbaa946f472/src/Network/Pusher/Internal/HTTP.hs#L48

**Comment by WillSewell** [comment]
Done. Thanks for reporting!
